global:
	need-to-collect: true #collect data from mongo to csv if not done already
	need-to-discrete: true #discretize numerical coluns if not done already
	cols-to-be-used: [] #cols to used for clustering



data: 
	mongo-conn-string: 'mongodb://localhost:27017/' #connection string for mongod
	mongo-db: 'demon_india' #mongo db containing demonetisation twitter data
	mongo-collection: 'user_info' #mongo collection containing user tweets
	file-collection: '../data/fc.csv' #file-collection results filename
	file-discrete: '../data/ds.csv' #discretisation results filename
	file-iterate: '../data/cc.csv' #conceptual clustering results filename
	file-analysis: '../data/ca.csv' #clusters analysis results filename

preprocess:
	num-cols: [] #numerical cols to be discretised
	max-groups: 10 #max_groups that can be made while discretisation
	hashtag-dict: 
	symbol-dict: 

ordering:
	topn: 10 #expected no of clusters used for ordering - number of elements for manhattan distance maximisation

tree:
	min-pop: 10 #min population of node

utility:

final-partition:

